name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          dart --version: '2.19.6'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --output firebase/public

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "firebase"
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ODMAFIA_FE0AD }}'
          channelId: live
          projectId: odmafia-fe0ad
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



