name: MyGithubActions
on:
  push:
    branches: 
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello
        run : echo "Hello world"


  deploy2: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello 2
        run : echo "Hello world 2"
    
